// PLANING, STARTED, FINISHED, CANCELED

export enum GameStatus {
  PLANING = "PLANING",
  DETAIL_CREATED = "DETAIL_CREATED",
  STARTED = "STARTED",
  FINISHED = "FINISHED",
  CANCELED = "CANCELED",
}
