// NOT_STARTED, CHARACTER_SELECTION, IN_PROGRESS, FINISHED
export enum WerewolvesGameStatus {
    NOT_STARTED = 'NOT_STARTED',
    CHARACTER_SELECTION = 'CHARACTER_SELECTION',
    IN_PROGRESS = 'IN_PROGRESS',
    FINISHED = 'FINISHED'
}
